### ISSUE TITLE
ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by Slaurits** [thejoabo/autofishbot#102]
whenever i start the bot with config correct it gives the following error
`C:\Users\lcv20\Desktop\Fish\autofishbot>python autofishbot.py
Traceback (most recent call last):
  File "C:\Users\lcv20\Desktop\Fish\autofishbot\autofishbot.py", line 4, in <module>
    from app import *
  File "C:\Users\lcv20\Desktop\Fish\autofishbot\app\__init__.py", line 7, in <module>
    from .api_wrapper import DiscordWrapper, APPLICATION_ID, TARGET_EVENT_NAMES, BUTTON, COMMAND
  File "C:\Users\lcv20\Desktop\Fish\autofishbot\app\api_wrapper.py", line 6, in <module>
    from .menu import NotificationPriority
  File "C:\Users\lcv20\Desktop\Fish\autofishbot\app\menu.py", line 9, in <module>
    import curses
  File "C:\Users\lcv20\AppData\Local\Programs\Python\Python311\Lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'`

It works on my pc at home but not my school one.

![image](https://user-images.githubusercontent.com/83727223/227872052-d3b6386f-5ffe-4ff0-b3fb-9a04bab5336f.png)

**Comment by Slaurits** [comment]
had to reinstall all of the requirements, because doing it with the txt didn't install all of them correctly
